Bootstrap flux secrets for installing Lets Encrypt issuer
equinor/radix-platform pull request #1158
Opened 2024-01-24 13:35 UTC by nilsgstrabo

- Bootstrap secret used by Flux to install cluster issuer for Lets Encrypt
-

2024-02-02 11:41 UTC, Richard87 requested changes

2024-02-02 11:41 UTC, Richard87 commented on scripts/cert-manager/bootstrap.sh
> +  RADIX_WILDCARD_CERTIFICATE_ISSUER: ${RADIX_WILDCARD_CERTIFICATE_ISSUER}
Move RADIX_WILDCARD_CERTIFICATE_ISSUER to postbuild in flux

2024-02-05 08:54 UTC, nilsgstrabo commented on scripts/cert-manager/bootstrap.sh
> +  RADIX_WILDCARD_CERTIFICATE_ISSUER: ${RADIX_WILDCARD_CERTIFICATE_ISSUER}
fixed

2024-02-05 11:37 UTC, Richard87 approved these changes
godkjent

2024-02-05 12:04 UTC, merged