Update flux bootstrap and env files
equinor/radix-platform pull request #1353
Opened 2024-05-31 08:43 UTC by emirgens

2024-05-31 12:32 UTC, Richard87 requested changes
We should change the hardcoded strings to follow the same convention, added some suggestions :)
ext-mon config is done in the radix-monitoring currently:
https://github.com/equinor/radix-monitoring/blob/master/cluster-external-monitoring/scripts/radix-zone/radix_zone_ext-mon.env

Maybe we should remove radix_zone_extmon.env to avoid confusion?

The rest looks good! 👍

2024-05-31 12:32 UTC, Richard87 commented on scripts/radix-zone/radix_zone_playground.env
> +AZ_COMMON_KEYVAULT="radix-keyv-playground"
```suggestion
AZ_COMMON_KEYVAULT="radix-keyv-${RADIX_ZONE}"
```

2024-05-31 12:32 UTC, Richard87 commented on scripts/radix-zone/radix_zone_dev.env
> +AZ_COMMON_KEYVAULT="radix-keyv-dev"
```suggestion
AZ_COMMON_KEYVAULT="radix-keyv-${RADIX_ZONE}"
```

2024-05-31 12:32 UTC, Richard87 commented on scripts/radix-zone/radix_zone_c2.env
> +AZ_COMMON_KEYVAULT="radix-keyv-c2"
```suggestion
AZ_COMMON_KEYVAULT="radix-keyv-${RADIX_ZONE}"
```

2024-06-03 06:32 UTC, sveinpj approved these changes

2024-06-03 07:18 UTC, merged