Gha storageaccount terraform
equinor/radix-platform pull request #848
Opened 2023-01-19 10:07 UTC by sveinpj

2023-01-20 13:02 UTC, emirgens commented on terraform/infrastructure/s941/storageaccounts/lab/resources.auto.tfvars
> +}
Should not be included

2023-01-20 13:02 UTC, emirgens commented on terraform/infrastructure/s941/storageaccounts/vnets.auto.tfvars
> +    subnet_name = "subnet-magnus-test"
Is this hardcoded? Test resources should not be included

2023-01-20 13:05 UTC, sveinpj commented on terraform/infrastructure/s941/storageaccounts/vnets.auto.tfvars
> +    subnet_name = "subnet-magnus-test"
Yes for now, but later  the new "migration" procedure set the these rules.

2023-01-20 13:56 UTC, sveinpj commented on terraform/infrastructure/s941/storageaccounts/lab/resources.auto.tfvars
> +}
Removed

2023-01-20 13:56 UTC, sveinpj commented on terraform/infrastructure/s941/storageaccounts/vnets.auto.tfvars
> +    subnet_name = "subnet-magnus-test"
Removed

2023-01-20 14:12 UTC, emirgens requested changes

2023-01-20 14:12 UTC, emirgens commented on terraform/infrastructure/s940/storageaccounts/main.tf
> +}
Not necessary anymore

2023-01-20 14:12 UTC, emirgens commented on terraform/infrastructure/s940/storageaccounts/main.tf
> +    name    = "Lifecycle-platform"
rename to lifecycle-prod (small letters)
(this is subscription context not cluster)

2023-01-20 14:12 UTC, emirgens commented on terraform/infrastructure/s940/storageaccounts/main.tf
> +  }
Not necessary - we have nothing in norway east

2023-01-20 14:12 UTC, emirgens commented on terraform/infrastructure/s940/storageaccounts/main.tf
> +  retention_duration = "P30D"
Nothing in norway east

2023-01-20 14:12 UTC, emirgens commented on terraform/infrastructure/s941/storageaccounts/main.tf
> +  resource_group_name = "common"
assume this will use the variables for names in next iteration

2023-01-20 14:12 UTC, emirgens commented on terraform/infrastructure/s941/storageaccounts/main.tf
> +  name               = "s941-azure-blob-backuppolicy-northeurope"
Good name? Is this really the policy? Or is it the blobs backed up based on the policy

2023-01-20 14:12 UTC, emirgens commented on terraform/infrastructure/s941/storageaccounts/sync.sh
>      echo "Uploadring terraform.state file..."
```suggestion
    echo "Uploading terraform.state file..."
```

2023-01-20 14:12 UTC, emirgens commented on terraform/radix-zone/s941-storageaccounts.tfvars
> +    rg_name       = "Logs-Dev"
correct res. group?

2023-01-24 11:25 UTC, sveinpj commented on terraform/radix-zone/s941-storageaccounts.tfvars
> +    rg_name       = "Logs-Dev"
Fix later

2023-01-24 11:26 UTC, sveinpj commented on terraform/infrastructure/s940/storageaccounts/main.tf
> +}
Resolved

2023-01-26 12:30 UTC, sondresjolyst approved these changes

2023-01-26 12:32 UTC, merged