Script to update new cluster OIDC reference
equinor/radix-platform pull request #966
Opened 2023-05-09 15:08 UTC by satr

2023-05-15 07:18 UTC, nilsgstrabo requested changes
Added some comments.
I also think it would be useful to have a dry-run/verify-only argument so we can get a list of apps/envs/components+jobs and if the clientId is correctly configured

2023-05-15 07:18 UTC, nilsgstrabo commented on scripts/aks/create-federated-credentials.sh
> +          fi
Don't think it is neccessary to do this check. The script should register the federated credentials even if none already exist.

2023-05-15 07:18 UTC, nilsgstrabo commented on scripts/aks/create-federated-credentials.sh
> +          requiredFedCredCount=$(echo "$fedCreds"|jq -r ".[]|select(.issuer|contains(\"$ISSUER_URL\"))"|jq -s ".|length")
You should check existiance of both issuer URL and subject here.

2023-05-15 07:18 UTC, nilsgstrabo commented on scripts/aks/create-federated-credentials.sh
> +          requiredFedCredCount=$(echo "$fedCreds"|jq -r ".[]|select(.issuer|contains(\"$ISSUER_URL\"))"|jq -s ".|length")
Need to check both issuer url and subject (One managed identity can be used by multiple components)

2023-05-16 10:50 UTC, emirgens commented on scripts/aks/create-federated-credentials.sh
> +          fi
Agree

2023-05-16 10:51 UTC, emirgens commented on scripts/aks/create-federated-credentials.sh
> +          fi
Agree

2023-05-16 10:51 UTC, emirgens commented on scripts/aks/create-federated-credentials.sh
> +        newFedCredSubject="system:serviceaccount:${namespace}:${componentName}-sa"
Keep it simple

2023-06-05 13:55 UTC, satr commented on scripts/aks/create-federated-credentials.sh
> +        newFedCredSubject="system:serviceaccount:${namespace}:${componentName}-sa"
Fixed

2023-06-05 13:56 UTC, satr commented on scripts/aks/create-federated-credentials.sh
> +          requiredFedCredCount=$(echo "$fedCreds"|jq -r ".[]|select(.issuer|contains(\"$ISSUER_URL\"))"|jq -s ".|length")
Fixed (this code was deleted now)

2023-06-05 13:56 UTC, satr commented on scripts/aks/create-federated-credentials.sh
> +          requiredFedCredCount=$(echo "$fedCreds"|jq -r ".[]|select(.issuer|contains(\"$ISSUER_URL\"))"|jq -s ".|length")
Fixed (this code was deleted now)

2023-06-05 13:56 UTC, satr commented on scripts/aks/create-federated-credentials.sh
> +          fi
Fixed

2023-06-05 13:57 UTC, satr commented on scripts/aks/create-federated-credentials.sh
> +          jq -r '.|select(.activeDeployment != null)|.activeDeployment as $depl|select($depl.components != null)|$depl.components[] as $comp|select($comp.identity != null)|select($comp.identity.azure
Jobs are in the same `components` list, as regular components, so they are in use

2023-06-21 07:40 UTC, nilsgstrabo approved these changes

2023-06-21 08:04 UTC, merged